name: d2l
channels:
  - defaults
dependencies:
  - python=3.9
  - pytorch-cuda=12.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - pytorch=2.5.1
  - scikit-learn
  - tqdm
prefix: /home/lenovo/miniconda3/envs/d2l
